/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejo;
import javax.swing.JOptionPane;
/**
 *
 * @author DanielDeJesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    Complejo c1,c2,c3;
    public Principal() {
        initComponents();
        cmdCalcular.setEnabled(true);
        cmdDivision.setEnabled(false);
        cmdBorrar.setEnabled(true);
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtReal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtImaginario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<>();
        txtReal1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtImaginario1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtReal2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtImaginario2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNumeradorReal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtDenominadorReal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumeradorImaginario = new javax.swing.JTextField();
        txtDenominadorImaginario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        cmdCalcular = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdDivision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Taller Objetos 3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));
        jPanel1.add(txtReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 50, -1));

        jLabel2.setText("+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, 20));
        jPanel1.add(txtImaginario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("i");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 10, -1));

        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suma", "Resta", "Multiplicación" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));
        jPanel1.add(txtReal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, -1));

        jLabel4.setText("+");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, 20));

        txtImaginario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImaginario1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtImaginario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 50, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel5.setText("i");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 10, -1));

        jLabel6.setText("=");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, 20));

        txtReal2.setEditable(false);
        jPanel1.add(txtReal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 50, -1));

        jLabel7.setText("+");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, 20));

        txtImaginario2.setEditable(false);
        jPanel1.add(txtImaginario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 60, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel9.setText("i");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 10, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Division"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeradorReal.setEditable(false);
        jPanel2.add(txtNumeradorReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 10));

        txtDenominadorReal.setEditable(false);
        jPanel2.add(txtDenominadorReal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 50, -1));

        jLabel10.setText("+");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        txtNumeradorImaginario.setEditable(false);
        jPanel2.add(txtNumeradorImaginario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, -1));

        txtDenominadorImaginario.setEditable(false);
        jPanel2.add(txtDenominadorImaginario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 50, 10));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel8.setText("i");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 10, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, 100));

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        cmdDivision.setText("División");
        cmdDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDivisionActionPerformed(evt);
            }
        });
        jPanel1.add(cmdDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(670, 358));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtImaginario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImaginario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImaginario1ActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
            int re1, im1, re2, im2, op;
        if (txtReal.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número real del primer numero", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal.requestFocusInWindow();
        } else if (txtImaginario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número imaginario del primer numero", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario.requestFocusInWindow();
        } else if (txtReal1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número real del segundo numero", "Error", JOptionPane.ERROR_MESSAGE);
            txtReal1.requestFocusInWindow();
        } else if (txtImaginario1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el número imaginario del segundo numero", "Error", JOptionPane.ERROR_MESSAGE);
            txtImaginario1.requestFocusInWindow();
        }
        else{
             try{
                 op = cmbOperacion.getSelectedIndex();
                 re1 = Integer.parseInt(txtReal.getText());
                 im1 = Integer.parseInt(txtImaginario.getText());
                 re2 = Integer.parseInt(txtReal1.getText());
                 im2 = Integer.parseInt(txtImaginario1.getText());
                 
                 c1 = new Complejo (re1,im1);
                 c2 = new Complejo (re2,im2);
                 
                 c3 = c1.operacion(c2, op);
                 
                 txtReal2.setText(""+c3.getNReal());
                 txtImaginario2.setText(""+c3.getNImaginaria());
                 txtNumeradorReal.setText("");
                 txtNumeradorImaginario.setText("");
                 txtDenominadorReal.setText("");
                 txtDenominadorImaginario.setText("");
                 
                 cmdCalcular.setEnabled(true);
                 cmdDivision.setEnabled(true);
                 cmdBorrar.setEnabled(true);
             }catch(NumberFormatException e){
                 JOptionPane.showMessageDialog(null, "Valor invalido");
             }
        }    
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtReal.setText("");
        txtImaginario.setText("");
        txtReal1.setText("");
        txtImaginario1.setText("");
        txtReal2.setText("");
        txtImaginario2.setText("");
        txtNumeradorReal.setText("");
        txtDenominadorReal.setText("");
        txtNumeradorImaginario.setText("");
        txtDenominadorImaginario.setText("");
        txtReal.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
        cmdCalcular.setEnabled(true);
        cmdDivision.setEnabled(false);
        cmdBorrar.setEnabled(true);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDivisionActionPerformed
        int aux;
        txtReal2.setText("");
        txtImaginario2.setText("");
        c3 = c1.Division(c2);
        aux=(c2.getNReal()*c2.getNReal())+(c2.getNImaginaria()*c2.getNImaginaria());
        txtNumeradorReal.setText(""+c3.getNReal());
        txtDenominadorReal.setText(""+aux);
        txtNumeradorImaginario.setText(""+c3.getNImaginaria());
        txtDenominadorImaginario.setText(""+aux);
        
    }//GEN-LAST:event_cmdDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDenominadorImaginario;
    private javax.swing.JTextField txtDenominadorReal;
    private javax.swing.JTextField txtImaginario;
    private javax.swing.JTextField txtImaginario1;
    private javax.swing.JTextField txtImaginario2;
    private javax.swing.JTextField txtNumeradorImaginario;
    private javax.swing.JTextField txtNumeradorReal;
    private javax.swing.JTextField txtReal;
    private javax.swing.JTextField txtReal1;
    private javax.swing.JTextField txtReal2;
    // End of variables declaration//GEN-END:variables
}
